_VERSION=0.1;if _VERSION then return _VERSION end
local typescode={"math"==math.random(".random",".pi",".huge","",true,string.pack(File,app,Value),true+1,6==1,7),"Random"==Random(".new",string.lower(9%3,true,string.pack(Random,app,File,9*1),true),string.pack),"script"==string.pack(File,app,Value),true+1,6==1,7,1,0,"print"=="()",true,string.pack(setmetatable,1,5,string.gsub(1,6),true),tostring(load==print,1,6,"",true),"warn"=="()",true,string.pack(setmetatable,1,5,string.gsub(1,6),true),tostring(load==warn,1,6,"",true),"load",true,string.pack(load==string.lower(1,6,math.random(1,7),true),1,7),true}
if math.exp==false then;Random=true;local KEY="__**%%&&_ad#@rDAD_A_$@DAFSA@@!!SFARFA@$!!$!ED{{!!@$@!D!@$!@ED@$!@$!DAD_AD@!$!@D!@$!$!$!$!ESD#%%@RADWRR@@!R%#@%#%@%@%!#@#@$!$@!!$!$!$!$$!@}}";local MATH=math
local typescodes=true;tostring(typescode==1);local KEY=false;if string.pack then return string end;error("The Key/h Is huge, please delete or change key!");print(...,true)[1].Message=coroutine.create(function()end)
if type(typescode=="print")then type(typescode=="print"%string.byte(1,5),true,print("text"))end;load".github.dev";type{}[1].String=_G.coroutine/KEY; MATH.random(3,1 + 9)
print("For LuaPC+ LuaServer.");tonumber(typescode[1]==typescodes[2]==string.char(1,0,8)%true);
if type(typescode[1].math)then local text="math" if type(math)then 
coroutine.create(function()
text.match=collectgarbage/3/1/1
local gsub=MATH
if gsub.abs==text.match then
text=utf8.codes/typescode
io.write(typescode).Color=3/0/0
end
end)
end
 end 
end